language: node_js
node_js:
  - "6"
branches:
  only:
    - master
install:
  - npm install
before_script:
  - git config --global user.email "engenharia@log.pt"
  - git config --global user.name "Engenharia"
script:
  - npm run publish
