language: node_js
node_js:
  - "6"
install:
  - npm install
before_script:
  - git config --global user.email "engenharia@log.pt"
  - git config --global user.name "Engenharia"
script:
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  email: engenharia@log.pt
  name: Engenharia
  local_dir: _book
  on:
    branch: master
