language: node_js
node_js:
  - "6"
install:
  - npm install
script:
  - npm build
  - npm run publish
before_deploy:
  - git config --global user.email "engenharia@log.pt"
  - git config --global user.name "Engenharia"
deploy:
  - npm run publish
